### ISSUE TITLE
grammatical error on question 10

### ISSUE THREAD

**Issue by ryanmeinzer** [learn-co-curriculum/programming-univbasics-2-case-statement#2]
"A case statement is an alternative statement to can be used to test for performing selection like if...elsif...elsif...end" should be "A case statement is an alternative statement that can be used to test for performing selection like if...elsif...elsif...end"

**Comment by maxwellbenton** [comment]
Hi @ryanmeinzer,

Thank you for spotting this and providing feedback. We've corrected the final question in [this quiz](https://github.com/learn-co-curriculum/programming-univbasics-2-quiz) and believe this issue is now resolved.

Thank you for contributing to a Learn lesson!
